def check_vowels():
    name = input("ingrese un nombre:")
    has_a = ("a" in name.lower())
    has_e = ("e" in name.lower())
    has_i = ("i" in name.lower())
    has_o = ("o" in name.lower())
    has_u = ("u" in name.lower())
    print (f"Contiene a: {has_a}")
    print (f"Contiene e: {has_e}")
    print (f"Contiene i: {has_i}")
    print (f"Contiene o: {has_o}")
    print (f"Contiene p: {has_u}")
